Updating snap to download latest spark version automatically.

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -69,13 +69,24 @@ parts:
     stage-packages:
         - openjdk-11-jre-headless
     override-build: |
-        SPARK_VERSION='3.3.0'
+        SPARK_VERSION=$(curl --silent https://downloads.apache.org/spark/ | grep "spark-" | cut -d'>' -f3 | cut -d'/' -f1  | sort | tail -n 1)
+        STATUSCODE=$(curl --silent --head https://downloads.apache.org/spark/${SPARK_VERSION}/${SPARK_VERSION}-bin-hadoop3.tgz | head -n 1 | cut -d' ' -f2)
+        echo "====================================="
+        echo ~${SPARK_VERSION}~
+        echo ~${STATUSCODE}~
+        echo "====================================="
+        if  [[ ${STATUSCODE} -ne 200 ]]
+          then
+            echo "ERROR: Latest available Spark version ${SPARK_VERSION} does not have a downloadable binary! Exiting...."
+            exit 1
+        fi
+        echo "Downloading latest available Spark version ${SPARK_VERSION}."
         SPARK_HADOOP_VERSION='3'
         AWS_JAVA_SDK_BUNDLE_VERSION='1.11.874'
         HADOOP_AWS_VERSION='3.2.2'
-        wget https://downloads.apache.org/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz
-        tar -zxf spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz
-        cd spark-${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}/jars
+        wget https://downloads.apache.org/spark/${SPARK_VERSION}/${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz
+        tar -zxf ${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz
+        cd ${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}/jars
         wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_JAVA_SDK_BUNDLE_VERSION}/aws-java-sdk-bundle-${AWS_JAVA_SDK_BUNDLE_VERSION}.jar
         wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar
         cd ..
