Addressing Jon's feedback, verifying checksums.

diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -69,26 +69,43 @@ parts:
     stage-packages:
         - openjdk-11-jre-headless
     override-build: |
+        SPARK_HADOOP_VERSION='3'
+        AWS_JAVA_SDK_BUNDLE_VERSION='1.11.874'
+        HADOOP_AWS_VERSION='3.2.2'
         SPARK_VERSION=$(curl --silent https://downloads.apache.org/spark/ | grep "spark-" | cut -d'>' -f3 | cut -d'/' -f1  | sort | tail -n 1)
-        STATUSCODE=$(curl --silent --head https://downloads.apache.org/spark/${SPARK_VERSION}/${SPARK_VERSION}-bin-hadoop3.tgz | head -n 1 | cut -d' ' -f2)
-        echo "====================================="
-        echo ~${SPARK_VERSION}~
-        echo ~${STATUSCODE}~
-        echo "====================================="
+        STATUSCODE=$(curl --silent --head "https://downloads.apache.org/spark/${SPARK_VERSION}/${SPARK_VERSION}-bin-hadoop3.tgz" | head -n 1 | cut -d' ' -f2)
         if  [[ ${STATUSCODE} -ne 200 ]]
           then
             echo "ERROR: Latest available Spark version ${SPARK_VERSION} does not have a downloadable binary! Exiting...."
             exit 1
         fi
         echo "Downloading latest available Spark version ${SPARK_VERSION}."
-        SPARK_HADOOP_VERSION='3'
-        AWS_JAVA_SDK_BUNDLE_VERSION='1.11.874'
-        HADOOP_AWS_VERSION='3.2.2'
-        wget https://downloads.apache.org/spark/${SPARK_VERSION}/${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz
-        tar -zxf ${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz
-        cd ${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}/jars
-        wget https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_JAVA_SDK_BUNDLE_VERSION}/aws-java-sdk-bundle-${AWS_JAVA_SDK_BUNDLE_VERSION}.jar
-        wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar
+        wget "https://downloads.apache.org/spark/${SPARK_VERSION}/${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz"
+        wget "https://downloads.apache.org/spark/${SPARK_VERSION}/${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz.sha512"
+        sha512sum --check "${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz.sha512"
+        if  [[ $? -ne 0 ]]
+          then
+            echo "DOWNLOAD ERROR: Latest available Spark version ${SPARK_VERSION} could not be downloaded properly! Exiting...."
+            exit 1
+        fi
+        tar -zxf "${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}.tgz"
+        cd "${SPARK_VERSION}-bin-hadoop${SPARK_HADOOP_VERSION}/jars"
+        wget "https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_JAVA_SDK_BUNDLE_VERSION}/aws-java-sdk-bundle-${AWS_JAVA_SDK_BUNDLE_VERSION}.jar"
+        wget "https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/${AWS_JAVA_SDK_BUNDLE_VERSION}/aws-java-sdk-bundle-${AWS_JAVA_SDK_BUNDLE_VERSION}.jar.sha1"        
+        echo "`cat aws-java-sdk-bundle-${AWS_JAVA_SDK_BUNDLE_VERSION}.jar.sha1`  aws-java-sdk-bundle-${AWS_JAVA_SDK_BUNDLE_VERSION}.jar" | sha1sum --check
+        if  [[ $? -ne 0 ]]
+          then
+            echo "DOWNLOAD ERROR: aws-java-sdk-bundle-${AWS_JAVA_SDK_BUNDLE_VERSION}.jar could not be downloaded properly! Exiting...."
+            exit 1
+        fi
+        wget "https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar"
+        wget "https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/${HADOOP_AWS_VERSION}/hadoop-aws-${HADOOP_AWS_VERSION}.jar.sha1"
+        echo "`cat hadoop-aws-${HADOOP_AWS_VERSION}.jar.sha1`  hadoop-aws-${HADOOP_AWS_VERSION}.jar" | sha1sum --check
+        if  [[ $? -ne 0 ]]
+          then
+            echo "DOWNLOAD ERROR: hadoop-aws-${HADOOP_AWS_VERSION}.jar could not be downloaded properly! Exiting...."
+            exit 1
+        fi
         cd ..
         mkdir -p $SNAPCRAFT_PRIME/bin
         cp -r bin/* $SNAPCRAFT_PRIME/bin/
@@ -113,10 +130,10 @@ parts:
       
       rm -rf "${target_dir}"
       mkdir -p "${target_dir}"
-      cp setup-spark-k8s.py "${target_dir}"/
-      chmod 755 "${target_dir}"/setup-spark-k8s.py
-      cp spark-submit.py "${target_dir}"/
-      chmod 755 "${target_dir}"/spark-submit.py
+      cp setup-spark-k8s.py "${target_dir}/"
+      chmod 755 "${target_dir}/setup-spark-k8s.py"
+      cp spark-submit.py "${target_dir}/"
+      chmod 755 "${target_dir}/spark-submit.py"
       
       mkdir -p "$SNAPCRAFT_PRIME/conf"
       cp spark-defaults.conf "$SNAPCRAFT_PRIME/conf/"
